# This workflow builds and tests the macOS Translate app
# The app requires macOS-specific frameworks (Carbon, Cocoa) and AppleScript

name: macOS Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: |
        # Ensure Xcode command line tools are available
        sudo xcode-select --install || true
        
    - name: Build for macOS
      run: |
        # Build with CGO enabled for Carbon framework
        # Set build tags for macOS to avoid Linux dependencies
        CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -v -tags darwin -o macostranslate-arm64 .
        CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -v -tags darwin -o macostranslate-amd64 .
        
    - name: Create universal binary
      run: |
        lipo -create -output macostranslate macostranslate-arm64 macostranslate-amd64
        
    - name: Test build
      run: |
        file macostranslate
        ./macostranslate --help
        
    - name: Run tests
      run: |
        # Note: Tests may be limited without a GUI environment
        go test -v ./... || echo "No tests found"
        
    - name: Create release package
      run: |
        # Create a tarball with all binaries
        if [ "${{ github.event_name }}" == "push" ]; then
          VERSION="${{ github.sha }}"
        else
          VERSION=$(date +%Y%m%d-%H%M%S)
        fi
        
        mkdir -p release
        cp macostranslate release/
        cp macostranslate-arm64 release/
        cp macostranslate-amd64 release/
        
        # Create checksums
        cd release
        shasum -a 256 macostranslate* > checksums.txt
        cd ..
        
        # Create tarball
        PACKAGE_NAME="macostranslate-${VERSION}.tar.gz"
        tar -czf "${PACKAGE_NAME}" -C release .
        
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "PACKAGE_NAME=${PACKAGE_NAME}" >> $GITHUB_ENV
        
    - name: Upload to GitHub Packages
      if: github.event_name == 'push'
      run: |
        # Create a release and upload the package
        gh release create "v$VERSION" \
          --title "macOS Translate v$VERSION" \
          --notes "Automated release of macOS Translate universal binary for commit ${{ github.sha }}" \
          --repo "${{ github.repository }}" \
          "$PACKAGE_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    # - name: Upload artifacts (for pull requests)
    #   if: github.event_name == 'pull_request'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: macostranslate-universal
    #     path: |
    #       macostranslate
    #       macostranslate-arm64
    #       macostranslate-amd64
    #       release/checksums.txt
